### ISSUE TITLE
EIP158 Progress

### ISSUE THREAD

**Issue by ayrat555** [poanetwork/mana#345]
- [x] [EIP155](https://github.com/ethereum/EIPs/issues/155) Replay attack protection - prevents transactions from one Ethereum chain from being rebroadcasted on an alternative chain. 
  - [x] [EIP160](https://github.com/ethereum/EIPs/issues/160) #346 EXP cost increase - adjusts the price of `EXP` opcode so it balances the price of `EXP` with the computational complexity of the operation, essentially making it more difficult to slow down the network via computationally expensive contract operations
  - [x] [EIP161](https://github.com/ethereum/EIPs/issues/161) State trie clearing - makes it possible to remove a large number of empty accounts that were put in the state at very low cost as a result of earlier DoS attacks. 
  - [x] [EIP170](https://github.com/ethereum/EIPs/issues/170) https://github.com/poanetwork/mana/pull/350 Contract code size limit - changes the maximum code size that a contract on the blockchain can have.
