### ISSUE TITLE
Networking progress

### ISSUE THREAD

**Issue by germsvel** [poanetwork/mana#407]
This is a high level issue to keep track of all the current knowledge of what is missing from our networking layer. This includes things like RLPx, DEVp2p, and Eth Wire Protocol. Any issues related to those three should be linked here. 

## To do
- [ ] Handle multi frame packets in ExWire https://github.com/poanetwork/mana/issues/97 
- [ ] Keep record of known peers https://github.com/poanetwork/mana/issues/99 
- [ ] Handle simultaneous auth for crypto handshake https://github.com/poanetwork/mana/issues/117 
- [ ] Handle DEVp2p message https://github.com/poanetwork/mana/issues/166
- [ ] Finish implementing Eth Wire Protocol https://github.com/poanetwork/mana/issues/167

## Resources

- [RLPx](https://github.com/ethereum/devp2p/blob/master/rlpx.md)
- [DEVp2p](https://github.com/ethereum/wiki/wiki/%C3%90%CE%9EVp2p-Wire-Protocol)
- [Eth Wire Protocol](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol)
- [EIP-8](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-8.md) which had changes to networking
